name: Auto Merge Pull Request

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for merge conflicts
        id: check-conflicts
        run: |
          git fetch origin master
          if git merge --no-commit --no-ff origin/master; then
            echo "has_conflict=false" >> $GITHUB_OUTPUT
            git merge --abort || true
          else
            echo "has_conflict=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Comment on PR if conflict exists
        if: steps.check-conflicts.outputs.has_conflict == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '❌ PR ini memiliki konflik dan tidak bisa di-merge. Silakan resolve konflik terlebih dahulu.'
            })

      - name: Check if PR modifies .txt files in nama_pelaku
        id: check-files
        if: steps.check-conflicts.outputs.has_conflict == 'false'
        run: |
          git fetch origin master
          changed_files=$(git diff --name-only origin/master HEAD)
          txt_in_nama_pelaku=false
          for file in $changed_files; do
            if [[ "$file" =~ ^nama_pelaku/.*\.txt$ ]]; then
              txt_in_nama_pelaku=true
              break
            fi
          done
          echo "txt_found=$txt_in_nama_pelaku" >> $GITHUB_OUTPUT

      - name: Comment if no valid .txt files found
        if: steps.check-conflicts.outputs.has_conflict == 'false' && steps.check-files.outputs.txt_found == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '❌ PR ini tidak mengubah file .txt di directory `nama_pelaku`. Harap tambahkan atau ubah minimal satu file .txt di directory tersebut agar bisa di-merge.'
            })

      - name: Auto merge PR
        if: steps.check-conflicts.outputs.has_conflict == 'false' && steps.check-files.outputs.txt_found == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge'
            });

      - name: Add success label
        if: steps.check-conflicts.outputs.has_conflict == 'false' && steps.check-files.outputs.txt_found == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['auto-merged']
            });
